/** @format */

import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import { Container, Row, Button } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pagina pesca || trabajo para geo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Layout>
          <Hero
            hrn1='#ques'
            hrn2='#QuePesca'
            hrn3='#tipos'
            hrn4='#objetivos'
            hrn5='#inidep'
            hrn6='#problematica'
            n1='La pesca'
            n2='Que se pesca'
            n3='Tipos de barcos y metodologias de pesca'
            n4='Objetivos'
            n5='Inidep'
            n6='Problematica | milla 201'
          />

          <Container className='mt-4' id='ques'>
            <Row className=' mb-5'>
              <div>
                <h1 className='fuente text-center'>La pesca</h1>
              </div>
              <div className=' titulo1'></div>
            </Row>
            <Container>
              <Row>
                <div className="col-12 col-lg-6 d-flex align-items-center mb-5">
                  <p className="text-center">
                  La actividad pesquera y acuícola consiste en la captura y cría de peces, crustáceos, moluscos y otros organismos de aguas saladas y dulces para aprovechar algunos recursos de la Naturaleza sin transformarlos. Estas actividades, además de proporcionar alimento, representan una fuente de ingresos.
                  </p>
                </div>
                <div className="col-12 col-lg-6 d-flex align-items-center mb-5">
                <Image
                    width={1920}
                    height={1159}
                    layout='intrinsic'
                    src='/img/pesca.jpg'
                  />
                </div>
              </Row>
            </Container>
          </Container>
          <Container className='mt-4 col-12' id='QuePesca' >
            <Row className=' mb-5'>
              <div>
                <h1 className='fuente text-center'>La pesca</h1>
              </div>
              <div className=' titulo1'></div>
            </Row>
            <Container>
              <Row>
                <div className="col-12 col-lg-6 d-flex align-items-center mb-5">
                <Image
                    width={1920}
                    height={1159}
                    layout='intrinsic'
                    src='/img/pesca.jpg'
                  />
                </div>
                <div className="col-12 col-lg-6 d-flex align-items-center mb-5">
                  <p className="text-center">
                  Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.
                  </p>
                </div>
              </Row>
            </Container>
          </Container>
          
        </Layout>
      </main>
    </>
  );
}
