/** @format */

import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Bootstrap1 from "../components/bootstrap/Bootstrap1";
import Bootstrap2 from "../components/bootstrap/Bootstrap2";
import Objetivos from "../components/Objetivos";
import Card1 from "../components/Card1";
import Swiper1 from "../components/swipers/Swiper1";
import { Container, Row } from "react-bootstrap";
import Swiper2 from "../components/swipers/Swiper2";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pagina pesca || trabajo para geo</title>
        <meta name='description' content='Generated by create next app' />
        <meta charset='UTF-8' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Layout>
          <Hero
            hrn1='#ques'
            hrn2='#QuePesca'
            hrn3='#tipos'
            hrn4='#objetivos'
            hrn5='#tiposDePesca'
            hrn6='#inidep'
            hrn7='#problematica'
            hrn8='#videos'
            n1='La pesca'
            n2='Que se pesca'
            n3='Tipos de barcos'
            n4='Objetivos'
            n5='tipos de pesca'
            n6='Inidep'
            n7='Problematica | milla 201'
            n8='videos'
          />

          <Container>
            <Row className=' mb-5 mt-5 ' id='ques'>
              <div className='d-flex titulo1 justify-content-center'>
                <h2 className='fuente '>La pesca</h2>
              </div>
            </Row>
            <Bootstrap2
              contedido='La actividad pesquera y acuícola consiste en la captura y
            cría de peces, crustáceos, moluscos y otros organismos de
            aguas saladas y dulces para aprovechar algunos recursos de
            la Naturaleza sin transformarlos. Estas actividades, además
            de proporcionar alimento, representan una fuente de
            ingresos.'
              direccion='/img/pesca.jpg'
            />
            <div id='QuePesca'></div>
          </Container>
          <section>
            <Container className='mt-4 col-12'>
              <Row className=' mb-5'>
                <div>
                  <h2 className='fuente text-center'>¿Que se pesca?</h2>
                </div>
                <div className=' titulo1'></div>
              </Row>
              <Container>
                <Row>
                  <div className='col-12 col-lg-6 d-flex align-items-center mb-5'>
                    <Image
                      width={1920}
                      height={1159}
                      layout='intrinsic'
                      src='/img/grafico-peces.png'
                      alt='grafico-peces'
                    />
                  </div>
                  <div className='col-12 col-lg-6 d-flex align-items-center mb-5'>
                    <p className='text-center fuente'>
                      La pesca en el Mar Argentino está compuesta principalmente
                      por peces, con una participación promedio del 69% en el
                      tonelaje de las capturas totales desde el inicio de los
                      2000 a 2019
                    </p>
                  </div>
                </Row>
              </Container>
            </Container>
            <div className='fondo-mar mb-5 mt-5'>
              <Swiper1></Swiper1>
            </div>
            <Container className='mb-5' id='merluza'>
              <Row>
                <div className='d-flex justify-content-center'>
                  <h3 className='text-center fuente'>Merluza</h3>
                </div>
                <div className=' titulo1'></div>
              </Row>
            </Container>
            <Container>
              <Row>
                <div className='col-12 col-lg-6 d-flex justify-content-center align-items-center'>
                  <div>
                    <p className=' fuente'>
                      La merluza hubbsi ha sido históricamente la principal
                      especie capturada, representando aproximadamente el 52% de
                      los peces en las últimas dos décadas. Otras especies de
                      importancia son la merluza de cola , la corvina blanca ,
                      la anchoíta , y la caballa. La merluza argentina fue de
                      las principales especies la que explicó el mayor dinamismo
                      de la actividad de la pesca marítima de la historia
                      argentina, en la década del 90. En ese mismo año, los
                      desembarques de merluza hubbsi representaron alrededor del
                      70% de las capturas totales de peces y el 33% de las
                      capturas totales de peces, moluscos y crustáceos . 2 Para
                      2019, el límite de captura de merluza al norte del
                      paralelo 41 S fue de 33.000 toneladas, mientras que para
                      el Sur del paralelo 41 S el tope para ese año fue de
                      280.000 toneladas. Los derechos relacionados con las
                      condiciones para pescar y explotar los recursos pueden ser
                      de acceso o de captura. Por su parte, los derechos de
                      captura, que establecen la intensidad de uso del recurso,
                      se dividen en derechos de esfuerzo, que definen por
                      ejemplo el tiempo de pesca, el tamaño del buque, tipos de
                      artes de pesca, etc., y los derechos de producto, que
                      determinan el nivel de captura permitida.
                    </p>
                  </div>
                </div>
                <div className='col-12 col-lg-6 '>
                  <Image
                    width={1920}
                    height={1159}
                    layout='intrinsic'
                    src='/img/merluza.png'
                    alt='merluza'
                  />
                  <p className='fuente'>
                    El macho alcanza su madurez con alrededor de 36 cm y con 40
                    cm en hembras. Se alimenta de peces más pequeños y habita a
                    una profundidad media de 200 m
                  </p>
                </div>
              </Row>
            </Container>
            <Container className='mb-5 mt-5' id='Anchoita'>
              <Row>
                <div className='col-12 d-flex'>
                  <div className=' col-6 d-flex justify-content-center'>
                    <h3 className='text-center fuente'>Caballa</h3>
                  </div>
                  <div className=' col-6 d-flex justify-content-center'>
                    <h3 className='text-center fuente'>Anchoita</h3>
                  </div>
                </div>
                <div className=' titulo1'></div>
              </Row>
            </Container>
            <Container>
              <Row>
                <div className='col-12 col-lg-6 '>
                  <Image
                    width={1920}
                    height={1159}
                    layout='intrinsic'
                    src='/img/caballa.png'
                    alt='caballa'
                  />
                  <h6 className='fuente'>
                    Mide entre 25 y 45 cm de longitud y puede alcanzar 4,5 kg de
                    peso.
                  </h6>
                  <h6 className='fuente'>
                    La caballa se alimenta de plancton, huevos de peces y
                    pequeños crustáceos.
                  </h6>
                  <h6 className='fuente'>
                    Vive en aguas abiertas cerca de la superficie. En primavera,
                    permanece en zonas cercanas a la costa.
                  </h6>
                </div>
                <div className='col-12 col-lg-6 '>
                  <Image
                    width={1920}
                    height={1159}
                    layout='intrinsic'
                    src='/img/anchoita.png'
                    alt='anchoita'
                  />
                  <h6 className='fuente'>
                    El rango de tallas para ambos sexos es de 14 a 19 cm. El
                    máximo observado es 21 cm en los adultos.{" "}
                  </h6>
                  <h6 className='fuente'>
                    se extiende sobre la plataforma continental del Atlántico
                    Sudoccidental, desde la latitud 24º Sur (San Pablo, Brasil),
                    hasta la latitud 48º Sur (Golfo de San Jorge en la patagonia
                    Argentina)
                  </h6>
                </div>
              </Row>
            </Container>
            <Container className='mb-5 mt-5' id='merluza-cola'>
              <Row>
                <div className='col-12 d-flex'>
                  <div className=' col-6 d-flex justify-content-center'>
                    <h3 className='text-center fuente'>Merluza de cola</h3>
                  </div>
                  <div className=' col-6 d-flex justify-content-center'>
                    <h3 className='text-center fuente'>Corvina blanca</h3>
                  </div>
                </div>
                <div className=' titulo1'></div>
              </Row>
            </Container>
            <Container>
              <Row>
                <div className='col-12 col-lg-6 '>
                  <Image
                    width={1920}
                    height={1159}
                    layout='intrinsic'
                    src='/img/merluza-cola.png'
                    alt='merluza-de-cola'
                  />
                  <h6 className='fuente'>
                    La talla máxima observada es de 117 cm de longitud total{" "}
                  </h6>
                  <h6 className='fuente'>
                    Su tamaño promiedo es de 59 y 56 cm de longitud
                  </h6>
                  <h6 className='fuente'>
                    Difiere de las otras merluzas por la forma de la cola, que
                    termina en punta por confluencia de las aletas dorsal y
                    anal.
                  </h6>
                </div>
                <div className='col-12 col-lg-6 '>
                  <Image
                    width={1920}
                    height={1159}
                    layout='intrinsic'
                    src='/img/corvina-blanca.png'
                    alt='corvina-blanca'
                  />
                  <h6 className='fuente'>
                    Su tamaño adulto oscila desde los 30 cm hasta incluso
                    superar los 2 m de longitud, pudiendo llegar a pesar más de
                    50 kilos en casos excepcionales.
                  </h6>
                  <h6 className='fuente'>
                    Su dieta incluye moluscos bivalvos, poliquetos, caracoles y
                    ocasionalmente crustáceos y peces como la anchoíta.
                  </h6>
                </div>
              </Row>
            </Container>
            <div id='tipos'></div>
          </section>

          <section>
            <Container>
              <Row className=' mb-5 mt-5'>
                <div className='d-flex titulo1 justify-content-center'>
                  <h2 className='fuente'>Tipos de barcos</h2>
                </div>
              </Row>

              <Row className='mb-4'>
                <div>
                  <div className='d-flex justify-content-center fuente'>
                    <h6 className='fuente'>
                      Puede considerarse un barco de pesca aquel objeto flotante
                      desde el que alguien saca un pez del agua mediante algún
                      tipo de arte. Los hay en los que solo cabe una silla y un
                      pequeño motor eléctrico, o bien, de los que se parecen más
                      a un transatlántico.{" "}
                    </h6>
                  </div>
                  <div>
                    <h6 className='fuente'>
                      Más allá del tipo de técnica o material que utilices para
                      obtener tus capturas, el tipo de barcos pesqueros cobra
                      gran importancia, ya sea una lancha para montar en un
                      remolque o un crucero por su autonomía para hacer más
                      horas de curricán y el equipamiento específico para pesca
                      de altura.
                    </h6>
                  </div>
                </div>
              </Row>

              <Bootstrap1
                direccion='/img/gomon.png'
                titulo='Embarcacion neumatica'
                contedido='Este tipo de embarcaciones debe contar tanto con un
                motor eléctrico como con unos remos, lejos de eso, la
                inversión es minima. Las embarcaciones neumáticas
                también pueden servir como complemento de un
                barco mayor para no realizar demasiados
                movimientos. Tienen un aforo de 1 a 2
                personas.'
              />
              <Bootstrap2
                direccion='/img/lancha-motor.jpg'
                titulo='Lancha a motor '
                contedido='La lancha es una embarcación pequeña de vela y remos, o bien de vapor o de motor (en estos casos, los más habituales hoy en día, se denomina lancha de motor). Este tipo de embarcación suele estar homologada para cinco personas y se caracteriza por ser muy estable y su facilidad de navegación, debido a sus líneas de casco.F'
              />
              <Bootstrap1
                direccion='/img/central.jpg'
                titulo='Barco de consola central'
                contedido='Es un tipo de barco de casco abierto de una sola cubierta donde el timón está en el centro.  Hay una cabina en algunos modelos; estos suelen estar situados en la proa y albergan pequeñas literas para dormir. Las literas pequeñas también pueden ubicarse dentro de la consola y debajo de la cubierta de los barcos con consola central más grandes.
                La mayoría de las consolas centrales funcionan con motores fuera de borda y pueden estar equipadas con uno o dos, lo que es común, hasta cinco o más en el caso de embarcaciones con consola central muy grandes.
                '
              />
              <Bootstrap2
                direccion='/img/Barco-cabinado-pequeño.png'
                titulo='Barco cabinado pequeño'
                contedido='El barco cabinado pequeño tiene unas dimensiones similares a las de la consola central. Sin embargo, el barco cabinado nos permite una mayor autonomía con la disposición de una cabina para poder pasar la noche en la embarcación.
                Este tipo de embarcación se caracteriza por tener una proa elevada en forma de V que facilita las condiciones de planeo y nos garantiza estar estables. Además, la bañera es amplia, donde la opción de los motores fueraborda aporta amplitud a la estiba interior, detalles que caracterizan a esta embarcación como una propia de pescadores1
                '
              />
              <Bootstrap1
                direccion='/img/catamaran1.jpg'
                titulo='Catamaran'
                contedido='Los catamaranes nos ofrecen una gran eslora y un lujoso habitáculo donde los haya. Esta embarcación no solo se adapta a la afición de la pesca, sino también de las múltiples comodidades que este te ofrece.
                Los dos cascos con los que cuenta aportan estabilidad en fondeo y en navegación. La separación entre motores permite un fácil movimiento que favorece especialmente a la pesca de altura.
                '
              />

              <Bootstrap2
                direccion='/img/barco-pesquero.jpg'
                titulo='Crucero de pesca.'
                contedido='Esta clase de crucero consta de más de 10 metros de eslora es el idóneo para la pesca de altura, además, nos da las comodidades que un barco de menores dimensiones no nos puede ofrecer.
                Destaca de estos cruceros la gran autonomía de la que disponen al tener unos mayores depósitos de combustible. Algunos cuentan con sistemas intra bordos que facilitan las maniobras dentro y fuera del puerto. Cabe destacar que la amplitud de este tipo de embarcación nos permite contar con un mayor aforo.
                '
              />
              <div id='objetivos'></div>
            </Container>
          </section>
          <section>
            <Objetivos></Objetivos>
            <div id='tiposDePesca'></div>
          </section>
          <section>
            <Container>
              <Row className=' mb-5 mt-5'>
                <div className='d-flex titulo1 justify-content-center'>
                  <h2 className='fuente'>Tipos de pesca</h2>
                </div>
              </Row>
              <Row>
                <Bootstrap1
                  direccion='/img/tipos-de-pesca.jpg'
                  titulo='Tipos de pesca'
                  contedido='Una pesquería está parcialmente definida por la forma en que se pesca. La elección de los artes de pesca juega un papel fundamental al determinar el costo, la eficiencia y la captura incidental de una pesquería.'
                />
              </Row>
            </Container>
            <div className='d-flex justify-content-center'>
              <h3 className='fuente '>Pesca con redes</h3>
            </div>
            <div className='d-flex justify-content-center mb-4'>
              <h6 className='fuente '>
                "Más del 80% de los peces son capturados usando estas redes. Sin
                embargo, hay muchos tipos diferentes"
              </h6>
            </div>
            <div className="d-flex justify-content-center">
              <h5 className='fuente mx-5 mb-3'>Red de cerco</h5>
            </div>
            <Container>
              <Row>
                <div className='d-flex justify-content-center'>
                  <p className='fuente'>
                    En la pesca con red de cerco, (la manera más común de
                    pescar), un barco localiza un cardumen de peces y luego, ya
                    sea usando una grúa o un barco pequeño, rodean el cardumen
                    con un extremo de la red y lo traen de vuelta a la
                    embarcación pesquera. Los extremos de la red se juntan, como
                    una bolsa con cordón, y se sube abordo con el pescado
                    adentro.
                  </p>
                </div>
              </Row>
              <Row>
                <div className='d-flex justify-content-center mb-5'>
                  <Image
                    width={500}
                    height={350}
                    layout='intrinsic'
                    src='/img/red-cerca.png'
                    alt='red'
                  />
                </div>
              </Row>
            </Container>
            <div>
              <h4 className='fuente mx-5 mb-3 text-center'>Arrastre</h4>
            </div>
            <div className='d-flex justify-content-center mb-4'>
              <p className='fuente '>
                Consiste en arrastrar una red a través del agua, detrás de un
                barco. Hay dos tipos diferentes: de fondo y pelágico
              </p>
            </div>
            <div className="d-flex justify-content-center mb-3">
              <h5>Arrastre de fondo</h5>
              <div></div>
            </div>

            <Container>
              <Row>
                <div className='d-flex justify-content-center'>
                  <p className='fuente'>
                    El arrastre de fondo consiste en hundir una red lastrada
                    hasta el fondo del mar para luego arrastrarla, barriendo el
                    fondo, y levantar el pescado. La captura incidental no es
                    demasiado preocupante en el caso delo arrastre de fondo,
                    pero el daño al hábitat sí lo es. Los fondos arenosos y los
                    ambientes rocosos se regeneran bastante rápido luego del
                    barrido por una red de arrastre, pero éstas pueden tener un
                    impacto significativo en hábitats sensibles como los corales
                    de aguas profundas o los jardines de esponjas. Una buena
                    gestión pesquera asegura que el arrastre de fondo se realice
                    en áreas sostenibles y no en lugares con hábitats
                    irremplazables.
                  </p>
                </div>
              </Row>
              <Row>
                <div className='d-flex justify-content-center mb-5'>
                  <Image
                    width={500}
                    height={350}
                    layout='intrinsic'
                    src='/img/arrastre-fondo.png'
                    alt='red'
                  />
                </div>
              </Row>
            </Container>
            <div className="d-flex justify-content-center mb-3">
              <h5>El arrastre pelágico</h5>
              <div></div>
            </div>
            <Container>
              <Row>
                <div className='d-flex mb-5 '>
                  <p className='fuente'>
                    El arrastre pelágico pasa la red por el agua, no en el
                    fondo. La captura incidental es baja.
                  </p>
                </div>
              </Row>
            </Container>
            <div>
              <h5 className="d-flex justify-content-center mb-3">Red de enmalle</h5>
            </div>
            <Container>
              <Row>
                <div className='d-flex justify-content-center'>
                  <p className='fuente'>
                    Las redes de enmalle son colocadas para ser una pared con
                    agujeros.. Los peces nadan a través de ella sin darse cuenta
                    y quedan atrapados.Las redes de enmalle tienen la mayor
                    captura incidental entre las redes de pesca, pero su uso
                    está en descenso.
                  </p>
                </div>
              </Row>
              <Row>
                <div className='d-flex justify-content-center mb-5'>
                  <Image
                    width={500}
                    height={350}
                    layout='intrinsic'
                    src='/img/enmalle.png'
                    alt='red'
                  />
                </div>
              </Row>
            </Container>




            <div className='d-flex justify-content-center'>
              <h3 className='fuente '>Pesca con linea</h3>
            </div>
            <div className="d-flex justify-content-center mb-3">
              <h5>Palangre</h5>
              <div></div>
            </div>

            <Container>
              <Row>
                <div className='d-flex justify-content-center'>
                  <p className='fuente'>
                  Los palangres son líneas muy largas que tienen anzuelos espaciados por una distancia de pocos pies. Pueden medir muchas millas de largo.Los problemas con el palangre son más frecuentes en pesquerías que operan cerca de la superficie donde aves marinas, tiburones y tortugas quedan atrapados por comer anzuelos cebados (con carnada).

                  </p>
                </div>
              </Row>
              <Row>
                <div className='d-flex justify-content-center mb-5'>
                  <Image
                    width={500}
                    height={350}
                    layout='intrinsic'
                    src='/img/linea-1.png'
                    alt='red'
                  />
                </div>
              </Row>
            </Container>

            <div className="d-flex justify-content-center mb-3">
              <h5>
Caña y línea
</h5>
              <div></div>
            </div>

            <Container>
              <Row>
                <div className='d-flex justify-content-center'>
                  <p className='fuente'>
                  Una caña y línea de pescar captura peces de manera individual. No hay problemas referentes a la captura incidental.
                  </p>
                </div>
              </Row>
              <Row>
                <div className='d-flex justify-content-center mb-5'>
                  <Image
                    width={500}
                    height={350}
                    layout='intrinsic'
                    src='/img/caña.png'
                    alt='red'
                  />
                </div>
              </Row>
            </Container>
          </section>

          <Container>
            <Row className=' mb-5 mt-5'>
              <div className='d-flex titulo1 justify-content-center'>
                <h2 className='fuente'>Inidep</h2>
              </div>
            </Row>
            <Container>
              <Row>
                <div className='col-12 col-lg-10 d-flex align-items-center mb-5'>
                  <Container>
                    <Row>
                      <div>
                        <p className='fuente'>
                          El Instituto Nacional de Investigación y Desarrollo
                          Pesquero** (INIDEP) asesora a la Subsecretaría de
                          Pesca y Acuicultura de la Nación (SSPyA), al Consejo
                          Federal Pesquero (CFP) y a la Cancillería Argentina en
                          el uso racional de los recursos pesqueros con el
                          objetivo de preservar el ecosistema marino para las
                          generaciones futuras.
                        </p>
                      </div>
                    </Row>
                    <div>
                      <p className='fuente'>
                        Las misiones y funciones son formular, ejecutar y
                        controlar los proyectos de investigación en prospección,
                        evaluación y desarrollo de pesquerías, de tecnologías de
                        acuicultura, de artes de pesca, de procesos tecnológicos
                        y en economía pesquera, conforme a las pautas y
                        prioridades que establezca la autoridad de aplicación.
                      </p>
                    </div>
                  </Container>
                </div>
                <div className=' inidep col-12 col-lg-2 d-flex align-items-center mb-5 pb-3'>
                  <Image
                    width={225}
                    height={225}
                    layout='intrinsic'
                    src='/img/inidep1.png'
                    alt='inidep'
                  />
                </div>
              </Row>
              <Bootstrap2
                direccion='/img/infraestructura.png'
                titulo='Infraestructura.'
                contedido='El edificio consta de tres áreas, que cubren 10650 Mts². La primera está formada por tres plantas unidas transversalmente. Aquí se ubican los gabinetes de trabajo de los investigadores y los laboratorios, que cuentan con equipamiento para efectuar sus tareas de acuerdo a los requerimientos de cada proyecto de investigación. También se encuentran la biblioteca, el aula chica, la sala de conferencias y el gabinete de fotografía, así como la dirección, las dependencias administrativas y la capitanía de armamento.
              '></Bootstrap2>
              <Bootstrap1
                direccion='/img/infraestructura2.png'
                contedido='La segunda área comprende la zona de taller y galpones, donde se almacenan los repuestos de los buques y los equipos de muestreo, que se utilizan en las campañas de investigación que realiza el Instituto. Desde allí, un portón se comunica con el muelle en el que amarran los buques de investigación del INIDEP, facilitando el acceso y el traslado del material desde y hacia los barcos.
              En la tercer área se ubica la estación experimental de maricultura, de dos plantas, con sus salas de acuarios, sectores de cría, laboratorios y gabinetes de trabajo.
              '></Bootstrap1>
              <Container>
                <Row>
                  <div className='d-flex justify-content-center'>
                    <h4 className='fuente'>historia de inidep</h4>
                  </div>
                </Row>
                <Row>
                  <div>
                    <p className='fuente'>
                      El Dr. Fernando Lahille fundó en 1898 el primer
                      laboratorio costero de biología marina, ubicado en Punta
                      Mogotes, Mar del Plata. En 1960, un grupo de
                      investigadores y docentes de las Universidades Nacionales
                      de Buenos Aires, La Plata y del Sur y del Poder Ejecutivo
                      de la Provincia de Buenos Aires (CIC) originaron el
                      Instituto de Biología Marina (IBM) en Playa Grande. En él
                      se constituyeron los primeros laboratorios en los que se
                      desarrollaron líneas básicas de investigación con equipos
                      de trabajo permanentes. El 21 de octubre de 1977 se creó
                      el INIDEP mediante la Ley 21.673 sobre la base del antiguo
                      Instituto de Biología Marina. Es un organismo
                      descentralizado de la Secretaría Agricultura, Ganadería y
                      Pesca, dependiente del Ministerio de Economía de la
                      Nación.
                    </p>
                    <p className='fuente'>
                      A fin de cumplir con los estudios necesarios, el INIDEP
                      posee actualmente tres buques de investigación pesquera,
                      el “Dr. Eduardo L. Holmberg”, el BIP "Víctor Angelescu" y
                      el BIP "Mar Argentino", equipados para la exploración de
                      extensas áreas marinas. La incorporación de estos buques
                      fue vital para la obtención de información continua y
                      especializada, imprescindible para el avance de las
                      investigaciones orientadas al manejo racional de los
                      recursos pesqueros.
                    </p>
                  </div>
                </Row>
                <Row>
                  <Swiper2></Swiper2>
                </Row>
              </Container>
              <div id='problematica'></div>
            </Container>
          </Container>
          <section>
            <Container>
              <Row className=' mb-5 mt-5'>
                <div className='d-flex titulo1 justify-content-center'>
                  <h2 className='fuente'>Problematica La milla 201</h2>
                </div>
              </Row>
              <Row>
                <div className='d-flex justify-content-center'>
                  <p className='fuente'>
                    Fuera de los monitores, en alta mar, cientos de miles de
                    toneladas de recursos marinos son extraídos anualmente por
                    buques extranjeros en el límite de la geografía y de la
                    legalidad. Estas flotas se ubican preferentemente en una
                    delgada franja donde la productividad y riqueza pesquera son
                    extraordinarias debido a los nutrientes transportados por la
                    corriente de Malvinas, que, en contacto con el talud
                    continental, ascienden a la superficie. La principal especie
                    capturada es el calamar, que migra a alta mar y, antes de
                    volver a ingresar en aguas nacionales, es presa de buques
                    “poteros” que provienen, en su mayoría, de China, Taiwán,
                    Corea y España.
                  </p>
                </div>
              </Row>
              <Bootstrap1
                direccion='/img/img-problematica.PNG'
                contedido='-El principal problema no es en si la pesca y los temas de legalidad(que de todas formas esta regulado por leyes), sino que la riqueza presente en esta zona por la corriente de Malvinas hace que puedan haber hasta 550 barcos pescando en esta franja, generando un marcado daño ambiental, y jugando con la extinción de especies.
                -Los barcos extranjeros reciben subsidios y ayudas de parte de sus estados lo que desestabiliza el mercado naval/pesquero, distorsionando el valor y los gastos de materiales y procesos.
                -Se concluye que para manejar mejor la situación se requiere una mayor presencia en todo lo que al océano pacifico se refiera, incluso lejos de nuestra jurisdicción, para poder evitar la desaparicion de especies y la disminución del campo de juego. 
                Pese a los esfuerzos de vigilancia, la flota pesquera que se instala al borde del Mar Argentino no para de crecer. Sólo por calamar se perdería más de USD 2.000 millones. Cifra que se quintuplica con el resto de las especies a lo largo del año.
                -En cuestiones legales en la ZEE(Zona Económica Exclusiva), miles de barcos ilegales desestabilizan la paz de la zona, complicando cuestionas económicas, de recursos y laborales. Estros barcos además suelen ser dificieles de detectar porque apagan sus sistemas de detección satetila, violando lo establecido por la Organización Martima Internacional (OMI)
                '></Bootstrap1>
            </Container>
            <div id='videos'></div>
          </section>
          <section>
            <Container className='mb-5'>
              <Row className=' mb-5 mt-5 ' id='ques'>
                <div className='d-flex titulo1 justify-content-center'>
                  <h2 className='fuente '>Videos</h2>
                </div>
              </Row>
              <Row>
                <div className='col-1'></div>
                <Card1
                  direccion='/img/inidep2.png'
                  titulo='Pesca industral'
                  contenido=''
                  link='https://youtu.be/wf1Vc3PSOy0'
                  boton='ir'></Card1>

                <div className='col-1'></div>
                <Card1
                  direccion='/img/mar.png'
                  titulo='Pesca ilegal'
                  contenido='pesca ilegal en la costa argentina'
                  link='https://youtu.be/jCCJQjEq4b8'
                  boton='ir'></Card1>
                <div className='col-1'></div>
                <Card1
                  direccion='/img/enrrique.png'
                  titulo='El calamar'
                  contenido='la pesca sustentable'
                  link='https://youtu.be/SQd6fJihjSc'
                  boton='ir'></Card1>
              </Row>
            </Container>
          </section>
        </Layout>
      </main>
    </>
  );
}
